fix: Component is missing template or render function
fix error in NetworkToast.vue component by adding empty template
error: Component is missing template or render function